eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
